### ISSUE TITLE
Add support for negative timecodes

### ISSUE THREAD

**Issue by RasmusBroborg** [RasmusBroborg/dotnet-timecode#11]
The current implementation of the timecode class does not support negative timecode-values. Theoretically the class should never be used with negative timelines, but assumptions usually lead to unwanted bugs in the future.

Ex of a negative timecode: "-10:00:00:00".

**Comment by leijon** [comment]
I can take a look at this. Please assign me to the issue.

**Comment by RasmusBroborg** [comment]
Hi @leijon,
You have been assigned to the issue.
