### ISSUE TITLE
Update ReadMe to include examples of operator overloading

### ISSUE THREAD

**Issue by RasmusBroborg** [RasmusBroborg/dotnet-timecode#25]
Include timecode operator overloading examples in ReadMe, as they will be included with the release of version 1.3.0.

Current overloaded operators are: + - < > == =! <= >=

**Comment by FaithKovi** [comment]
Hello, @RasmusBroborg I will like to work on this issue. Please assign

**Comment by RasmusBroborg** [comment]
Hi @FaithKovi, 
You have been assigned to the issue.

**Comment by hiteshbhavsar** [comment]
Hello @RasmusBroborg Can I work on this?

**Comment by FaithKovi** [comment]
Hello @RasmusBroborg I won't be working on this issue.

**Comment by RasmusBroborg** [comment]
@FaithKovi Thank you for letting us know you are no longer participating. 
@hiteshbhavsar I will assign you to the issue. Please use the other examples in the ReadMe for reference when adding to the ReadMe

**Comment by RasmusBroborg** [comment]
Fixed in #40
