### ISSUE TITLE
operator > doesn't throw if FrameRates are not equal

### ISSUE THREAD

**Issue by iSazonov** [RasmusBroborg/dotnet-timecode#30]
No check exists to throw InvalidOperationException

https://github.com/RasmusBroborg/dotnet-timecode/blob/e03b60af05847e18e4bff76d817c3fff4e670346/src/timecode/Timecode.cs#L315-L327

**Comment by RasmusBroborg** [comment]
Thank you for reporting this. This should be implemented before releasing the next version update.

Comment if you would like to to be assigned to the issue.

**Comment by RasmusBroborg** [comment]
After thinking about this I am questioning what behavior should be expected.

One could argue that a timecode with one framerate should be comparable to a timecode with another framerate, as they both are a representation of total frames.

Nevertheless, the current implementation still does not function as expected and need to be revised, so this is currently very much a bug.

**Comment by RasmusBroborg** [comment]
The current implementation will not accept comparison operator between different framerates to avoid confusion. I will submit a pull request shortly which implements a bugfix for the issue.
